### ISSUE TITLE
chatgpt 彻底不能用了，安装插件以后，chatgpt的主页和设置都消失了

### ISSUE THREAD

**Issue by Yrwxru** [qunash/chatgpt-advanced#158] opened 2023-04-23 17:21 UTC

**Comment by qunash** [comment] 2023-04-23 17:51
Hi, this is caused by the latest changes to the chatgpt UI. It's fixed in the latest version 3.2.7, it's currently under review in the web stores, should be available within couple of days.

**Comment by Yrwxru** [comment] 2023-04-24 02:33
好的，十分感谢，信息已经获知。

qunash ***@***.***> 于2023年4月24日周一 01:51写道：

**Comment by Runcoco** [comment] 2023-05-07 01:05
I have same issue. My chatGPT can not used now.   How to uninstall the webchatGPT and return to the original version.

**Closed** 2023-05-07 17:19 UTC

**Comment by Yrwxru** [comment] 2023-05-09 08:51
1、I was using Microsoft edge at the time, just switched to Google Chrome.
2、There is also a possibility that the proxy has been blocked, just switch
a node.

qunash ***@***.***> 于2023年5月8日周一 01:19写道：
